### ISSUE TITLE
<meiHead> metadata not rendering

### ISSUE THREAD

**Issue by tadoogie** [mei-friend/mei-friend#40] opened 2023-09-06 12:17 UTC
**Error Code**
None.

**Describe the bug**
I cannot get the Verovio renderer to display metadata from <meiHead>. Changing the value for 'Header' in the Verovio settings does not correct the problem. 

**To Reproduce**
1. Select an MEI file with metadata in <meiHead> (i.e., title, composer, etc.), but make sure it does not have any <rend> elements.
2. Load the file into mei-friend

**Expected behavior**
In the Verovio editor, basic metadata under <meiHead> shows appropriately and can be edited. The same behaviour would be expected here.

**Screenshots**
![mei-friend-Ps59-xml](https://github.com/mei-friend/mei-friend/assets/26714097/7dbc22c6-b013-409d-b485-c5c9cb05bd51)
![Verovio-Editor](https://github.com/mei-friend/mei-friend/assets/26714097/1c414533-13ee-4d92-8954-c1df77647116)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 116

**Additional context**
None.

**Comment by wergo** [comment] 2023-09-07 09:33
Thanks for raising this issue. 

It is caused by mei-friend, always loading its default Verovio options and ignoring the user-specific settings. 

An ad-hoc work-around for now would be: 
1) set option `header` to `auto` in the Verovio settings. 
2) Toggle speedMode button

Will be fixed soon.

**Comment by wergo** [comment] 2023-09-19 19:05
Fixed through e6dee28b97a875f31cba0aba3c4ffb0c580bbe4a.

**Closed by wergo** 2023-09-19 19:05 UTC
Labels: bug
